config/routes.rb
Rails.application.routes.draw do
  root to: 'games#index'
  resources :games, only: [:index, :new, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rank.rb
class Rank < ApplicationRecord
  validates :time, presence: true
  validates :nickname, presence: true
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  validates :text5, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def new
    @sentences = Sentence.order("RAND()").limit(10).pluck(:text5)
    render json: @sentences
    @rank = Rank.new
  end

  def create
    @rank = Rank.new(rank_params)
    if @rank.save
      redirect_to game_path
    else
      render 'new'
    end
  end

  def show
    @rank = Rank.find(params[:id])
  end

  private

  def rank_params
    params.require(:rank).permit(:time, :nickname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1 class="game-title" id="main-title">タイトル</h1>
<div class="button">
  <%= link_to "スタート", new_game_path, method: :get, id: "start-button", class: "btn btn-primary" %>
  <%= link_to "ランキング", "#", method: :get, id: "ranking-button", class: "btn btn-primary" %>

app/views/games/new.html.erb
<!-- プレイ画面 -->
<div id="game">
  <label for="inputText">
    <!-- 入力するべき単語が表示される部分 -->
    <div id="word-display">
      <span id="entered" class="maker"></span>
      <span id="remained"></span>
    </div>

    <!-- 入力欄 -->
    <input type="text" class= "text" id="inputText" autofocus>
  </label>


    <!-- ゲーム終了時に表示されるボタン -->
  <div id="message" class="text-container hidden">
    <div id = "time" ></div>
    <div class="button">
      <%= link_to "もう一度遊ぶ", "#", id: "replayBtn", class: "btn btn-primary" %>
      <%= link_to "メニューに戻る", "#", id: "menu-button", class: "btn btn-primary" %>
      <%= link_to "ランキングを保存", "/games/new", method: :get, id: "save-ranking-button", class: "btn btn-primary" %>
    </div>
  </div>

  <!-- 入力フォーム画面 -->
  <%= form_with model: @rank, local: true do |form| %>
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
    
    <%= form.submit "送信" %>
  <% end %>
</div>

app/views/games/show.html.erb
<!-- ランキング画面 -->
<% @ranks.order(time: :asc).each_with_index do |rank, index| %>
  <p><%= index + 1 %>. <%= rank.nickname %> - <%= rank.time %></p>
<% end %>

<!-- メニューに戻るボタン -->
<button id="menu-button2">メニューに戻る</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ぱたぱた</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "games", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>